{
 "title": "LOTUS farcaster",
 "description": "A Filecoin lotus dashboard for miners",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job:",
    "query": "label_values(lotus_miner_info{},job)"
   },
   {
    "name": "miner_id",
    "label": "Miner ID",
    "query": "label_values(lotus_miner_info{job=\"$job\"},miner_id)"
   },
   {
    "name": "worker_addr",
    "label": "Worker Address",
    "query": "label_values(lotus_miner_info{miner_id=\"$miner_id\"},worker_addr)"
   },
   {
    "name": "owner_addr",
    "label": "Owner Address",
    "query": "label_values(lotus_miner_info{miner_id=\"$miner_id\"},owner_addr)"
   },
   {
    "name": "control0_addr",
    "label": "Control Address 0",
    "query": "label_values(lotus_miner_info{miner_id=\"$miner_id\"},control0_addr)"
   },
   {
    "name": "worker_host",
    "label": "Worker",
    "query": "query_result(sort(lotus_miner_worker_cpu{miner_id=\"$miner_id\"}))"
   },
   {
    "name": "storage_id",
    "label": "Storage",
    "query": "label_values(lotus_miner_storage_info{miner_id=\"$miner_id\"},storage_id)"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status on",
   "type": "table",
   "description": "Status if error it means the last update was in error\nLast update is the last time that lotus-farcaster has been executed on the miner",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "lotus_local_time{job=\"$job\"}",
     "legendFormat": "Last update"
    },
    {
     "expr": "lotus_scrape_execution_succeed{job=\"$job\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Power estimation",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "1/(sum(lotus_power{miner_id=\"$miner_id\", scope=\"miner\", power_type=\"QualityAdjPower\"})/sum(lotus_power{miner_id=\"$miner_id\", scope=\"network\",power_type=\"QualityAdjPower\"})*2*5/60)"
    },
    {
     "expr": "sum(lotus_power{miner_id=\"$miner_id\", scope=\"miner\", power_type=\"QualityAdjPower\"})/sum(lotus_power{miner_id=\"$miner_id\", scope=\"network\",power_type=\"QualityAdjPower\"})*5*60*2*24"
    },
    {
     "expr": "sum(lotus_power{miner_id=\"$miner_id\", scope=\"miner\", power_type=\"QualityAdjPower\"})/sum(lotus_power{miner_id=\"$miner_id\", scope=\"network\",power_type=\"QualityAdjPower\"})"
    }
   ]
  },
  {
   "title": "Deadlines",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lotus_miner_deadline_active_start{miner_id=\"$miner_id\"}"
    },
    {
     "expr": "lotus_miner_deadline_active_sectors_all{miner_id=\"$miner_id\"}"
    },
    {
     "expr": "lotus_miner_deadline_active_sectors_recovering{miner_id=\"$miner_id\"}"
    },
    {
     "expr": "lotus_miner_deadline_active_sectors_faulty{miner_id=\"$miner_id\"}"
    },
    {
     "expr": "lotus_miner_deadline_active_partitions{miner_id=\"$miner_id\"}-lotus_miner_deadline_active_partitions_proven{miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "title": "Available Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "FIL" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_wallet_balance{miner_id=\"$miner_id\", address=\"$miner_id\"}",
     "legendFormat": "Miner"
    },
    {
     "expr": "lotus_wallet_balance{miner_id=\"$miner_id\", address=\"$owner_addr\"}",
     "legendFormat": "Owner"
    },
    {
     "expr": "lotus_wallet_balance{miner_id=\"$miner_id\", address=\"$worker_addr\"}",
     "legendFormat": "Worker"
    },
    {
     "expr": "lotus_wallet_balance{miner_id=\"$miner_id\", address=\"$control0_addr\"}",
     "legendFormat": "Control0"
    }
   ]
  },
  {
   "title": "Locked Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Fil" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_wallet_locked_balance{miner_id=\"$miner_id\"}",
     "legendFormat": "{{locked_type}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_chain_height{miner_id=\"$miner_id\"}",
     "legendFormat": "Chain Head"
    }
   ]
  },
  {
   "title": "Is onSync",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lotus_chain_sync_status{miner_id=\"$miner_id\"}",
     "legendFormat": "Worker {{ worker_id }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "lotus_power_mining_eligibility{miner_id=\"$miner_id\"}",
     "legendFormat": "Mining"
    }
   ]
  },
  {
   "title": "Miner Power",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_power{miner_id=\"$miner_id\", scope=\"miner\"}",
     "legendFormat": "{{power_type}}"
    },
    {
     "expr": "sum( lotus_miner_deadline_active_sectors_live{miner_id=\"$miner_id\"} * on(miner_id) group_left () lotus_miner_info_sector_size{miner_id=\"$miner_id\"})",
     "legendFormat": "Committed Power"
    }
   ]
  },
  {
   "title": "Netpeers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "lotus_netpeers_total{miner_id=\"$miner_id\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "lotus_miner_netpeers_total{miner_id=\"$miner_id\"}",
     "legendFormat": "Miner"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_mpool_local_total{miner_id=\"$miner_id\"}",
     "legendFormat": "Local mpool pending"
    }
   ]
  },
  {
   "title": "Local Mpool Pending messages",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "lotus_mpool_local_message{miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "lotus_mpool_total{miner_id=\"$miner_id\"}",
     "legendFormat": " Mpool pending"
    }
   ]
  },
  {
   "title": "Deals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sealing Deals",
     "type": "table",
     "gridPos": { "h": 5, "w": 16, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lotus_miner_sector_sealing_deals_size{miner_id=\"$miner_id\"}  * on (sector_id) group_left(state) (lotus_miner_sector_state{miner_id=\"$miner_id\"})\n"
      }
     ]
    }
   ]
  },
  { "title": "Sealing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Sealing jobs All (Running VS Idle)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Sectors" }
   ],
   "targets": [
    {
     "expr": "# REtourne le nombre de JOB dans l'etat running\ncount by (task) (lotus_miner_worker_job{miner_id=\"$miner_id\",run_wait=\"0\"})",
     "legendFormat": "{{ task }}"
    },
    {
     "expr": "count by (state) (lotus_miner_sector_state{miner_id=\"$miner_id\", state!~\"(Proving|Removed)\"} unless on (sector_id) lotus_miner_worker_job{miner_id=\"$miner_id\",run_wait=\"0\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "RUNNING Sealing Sectors",
   "type": "table",
   "gridPos": { "h": 21, "w": 9, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "# Retourne la liste de tout les jobs \"Running\" enrichi aves les informations deals and creation date recuperer depuis la liste des sectors\nlotus_miner_worker_job{miner_id=\"$miner_id\",run_wait=\"0\"} * on (sector_id) group_left(deals,creation_date) (lotus_miner_sector_state{miner_id=\"$miner_id\",state!~\"(Proving|Removed)\"})*1"
    },
    {
     "expr": "# Retourne la liste des jobs en cours \"Running\" pour lesquels il n'a a pas encore des secteurs (Les premiers AP par exemple) \nlotus_miner_worker_job{run_wait=\"0\"} unless on (sector_id) (lotus_miner_sector_state{miner_id=\"$miner_id\",state!~\"(Proving|Removed)\"})*1"
    },
    {
     "expr": "# Calcul do 95 centile sur 30 jours des jobs par Worker et Par task et calcul le temps restant pour chacun des jobs\nlotus_miner_worker_job{miner_id=\"$miner_id\",run_wait=\"0\"} - on(worker_host,task) group_left()(quantile(0.95,(max_over_time(lotus_miner_worker_job{miner_id=\"$miner_id\",worker_host!=\"\", run_wait=\"0\"}[30d]) > 1)) by (worker_host,task))"
    },
    {
     "expr": "# Retourne la date de creation du secteur\nlotus_miner_sector_event{event_type=\"creation\"} and on(sector_id) lotus_miner_worker_job{run_wait=\"0\"} "
    }
   ]
  },
  {
   "title": "IDLE Sealing Sectors",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "# Retourne tout les secteurs qui sont sur les workers mais dans un statut different de Running. On les enrichis avec les infos des workers (Assigned par exemple)\n(lotus_miner_sector_state{miner_id=\"$miner_id\", state!~\"(Proving|Removed)\"} * on (sector_id) group_left(job_id,run_wait,job_start_time,task,worker) lotus_miner_worker_job{miner_id=\"$miner_id\", run_wait!=\"0\"})*1"
    },
    {
     "expr": "# Retourne les jobs qui sont sur les worker dans un etat different de Running et qui seraient absent de la liste des secteurs (pas sur que ca existe)\n(lotus_miner_worker_job{miner_id=\"$miner_id\", run_wait!=\"0\"} unless on (sector_id) (lotus_miner_sector_state{miner_id=\"$miner_id\", state!~\"(Proving|Removed)\"}))*1"
    },
    {
     "expr": "# Retourne la liste des secteurs qui ne sont pas dans la liste des Jobs (Comme le WAitSeed, WaitCommit, mais aussi d'autres qui traine)\n# Les label_replace servent a creer des colonnes à 0 au cas ou la premiere requete ne retourne rien\n(label_replace(label_replace(label_replace(label_replace(label_replace(lotus_miner_sector_state{miner_id=\"$miner_id\", state!~\"(Proving|Removed)\"},\"job_id\",\"0\",\"\",\"\"),\"run_wait\",\"98\",\"\",\"\"),\"job_start_time\",\"0\",\"\",\"\"),\"task\",\"0\",\"\",\"\"),\"worker\",\"0\",\"\",\"\") unless on (sector_id) lotus_miner_worker_job{miner_id=\"$miner_id\"})*1"
    },
    {
     "expr": "# Retourne la date de creation pour les secteurs. Ici on filtre sur les 2 requetes principales precendente and AND et on les unis avec OR. Les requetes precendetes se terminent par *1 pour perdre le nom de la metrics et s'assurer que la transformation Merge fonctionne.\n((lotus_miner_sector_event{miner_id=\"$miner_id\", event_type=\"creation\"})  and  on (sector_id) lotus_miner_worker_job{miner_id=\"$miner_id\", run_wait!=\"0\"}) or ((lotus_miner_sector_event{miner_id=\"$miner_id\", event_type=\"creation\"})  and  on (sector_id) (lotus_miner_sector_state{miner_id=\"$miner_id\", state!~\"(Proving|Removed)\"} unless on (sector_id) lotus_miner_worker_job{miner_id=\"$miner_id\"}))"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lotus_miner_storage_info{miner_id=\"$miner_id\"}"
    },
    {
     "expr": "lotus_miner_storage_available{miner_id=\"$miner_id\"} "
    },
    {
     "expr": "lotus_miner_storage_available{miner_id=\"$miner_id\"} /lotus_miner_storage_capacity{miner_id=\"$miner_id\"} "
    }
   ]
  },
  {
   "title": "Average Sealing Duration (From Packed to Finalized)",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "expr": "quantile(0.5, (topk(10,lotus_miner_sector_event{miner_id=\"$miner_id\", event_type=\"finalized\"}) - on (sector_id) lotus_miner_sector_event{miner_id=\"$miner_id\", event_type=\"packed\"}) and on(sector_id) lotus_miner_sector_state{miner_id=\"$miner_id\", state=\"Proving\"})",
     "legendFormat": "Last 10 Sectors"
    },
    {
     "expr": "quantile(0.5, (topk(100,lotus_miner_sector_event{miner_id=\"$miner_id\", event_type=\"finalized\"}) - on (sector_id) lotus_miner_sector_event{miner_id=\"$miner_id\", event_type=\"packed\"}) and on(sector_id) lotus_miner_sector_state{miner_id=\"$miner_id\", state=\"Proving\"})",
     "legendFormat": "Last 100 Sectors"
    },
    {
     "expr": "quantile(0.5, (lotus_miner_sector_event{miner_id=\"$miner_id\", event_type=\"finalized\"} - on (sector_id) lotus_miner_sector_event{miner_id=\"$miner_id\", event_type=\"packed\"}) and on(sector_id) lotus_miner_sector_state{miner_id=\"$miner_id\", state=\"Proving\"})",
     "legendFormat": "All times"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count (lotus_miner_worker_cpu{miner_id=\"$miner_id\"})",
     "legendFormat": "Number of Workers"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by (state) (lotus_miner_sector_state{miner_id=\"$miner_id\", state=\"Proving\"})",
     "legendFormat": "Proving Sectors"
    }
   ]
  },
  {
   "title": "Number of sectors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by (state) (lotus_miner_sector_state{miner_id=\"$miner_id\", state!~\"(Proving)\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Ressources - $worker_host",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 38 },
   "repeat": "worker_host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg((lotus_miner_worker_cpu_used{miner_id=\"$miner_id\", worker_host=\"$worker_host\"})/(lotus_miner_worker_cpu{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}) >= 0)",
     "legendFormat": "CPU"
    },
    {
     "expr": "avg((lotus_miner_worker_gpu_used{miner_id=\"$miner_id\", worker_host=\"$worker_host\"})/(lotus_miner_worker_gpu{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}) >= 0)",
     "legendFormat": "GPU"
    },
    {
     "expr": "avg((lotus_miner_worker_mem_reserved{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}+lotus_miner_worker_mem_physical_used{miner_id=\"$miner_id\", worker_host=\"$worker_host\"})/(lotus_miner_worker_mem_physical{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}) >= 0)",
     "legendFormat": "RAM"
    },
    {
     "expr": "avg((lotus_miner_worker_mem_reserved{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}+lotus_miner_worker_mem_vmem_used{miner_id=\"$miner_id\", worker_host=\"$worker_host\"})/(lotus_miner_worker_mem_physical{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}+lotus_miner_worker_mem_swap{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}) >= 0)",
     "legendFormat": "VMEM"
    }
   ]
  },
  { "title": "Sealing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 170 } },
  {
   "title": "Sealing jobs - RUNNING",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Sectors" }
   ],
   "targets": [
    {
     "expr": "# REtourne le nombre de JOB dans l'etat running\ncount by (task) (lotus_miner_worker_job{miner_id=\"$miner_id\",run_wait=\"0\"})",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Sealing jobs - IDLE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Sectors" }
   ],
   "targets": [
    {
     "expr": "count by (state) ((lotus_miner_sector_state{miner_id=\"$miner_id\", state!~\"(Proving|Removed)\"}) unless on (sector_id) lotus_miner_worker_job{miner_id=\"$miner_id\",run_wait!=\"0\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Sealing ERRORS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Sectors" }
   ],
   "targets": [
    {
     "expr": "count by (state) (lotus_miner_sector_state{miner_id=\"$miner_id\" })",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Wallets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 178 } },
  {
   "title": "Available Balance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "FIL" } },
   "yaxes": [
    { "format": "FIL" }
   ],
   "targets": [
    {
     "expr": "lotus_wallet_balance{miner_id=\"$miner_id\", address=\"$miner_id\"}",
     "legendFormat": "Miner"
    },
    {
     "expr": "lotus_wallet_balance{miner_id=\"$miner_id\", address=\"$owner_addr\"}",
     "legendFormat": "Owner"
    },
    {
     "expr": "lotus_wallet_balance{miner_id=\"$miner_id\", address=\"$worker_addr\"}",
     "legendFormat": "Worker"
    },
    {
     "expr": "lotus_wallet_balance{miner_id=\"$miner_id\", address=\"$control0_addr\"}",
     "legendFormat": "Control0"
    }
   ]
  },
  {
   "title": "Locked Balance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "Fil" } },
   "yaxes": [
    { "format": "Fil" }
   ],
   "targets": [
    {
     "expr": "lotus_wallet_locked_balance{miner_id=\"$miner_id\"}",
     "legendFormat": "{{locked_type}}"
    }
   ]
  },
  {
   "title": "Other Wallet Balances",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "Fil" } },
   "yaxes": [
    { "format": "Fil" }
   ],
   "targets": [
    {
     "expr": "lotus_wallet_balance {miner_id=\"$miner_id\",address!~\"$worker_addr|$owner_addr|$control0_addr|$miner_id\"}",
     "legendFormat": "{{short}}"
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 185 } },
  {
   "title": "Miner Total Trafic ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 186 },
   "yaxes": [
    { "format": "bps", "label": "Bits out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(lotus_miner_net_total_in{miner_id=\"$miner_id\"}[5m])",
     "legendFormat": "Receive"
    },
    {
     "expr": "rate(lotus_miner_net_total_out{miner_id=\"$miner_id\"}[5m])",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Miner Total Trafic  per protocol",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 186 },
   "yaxes": [
    { "format": "bps", "label": "Bits out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(lotus_miner_net_protocol_in{miner_id=\"$miner_id\"}[5m])",
     "legendFormat": "{{protocol}} - Receive"
    },
    {
     "expr": "rate(lotus_miner_net_protocol_out{miner_id=\"$miner_id\"}[5m])",
     "legendFormat": "{{protocol}} - Transmit"
    }
   ]
  },
  {
   "title": "Netpeers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "lotus_netpeers_total{miner_id=\"$miner_id\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "lotus_miner_netpeers_total{miner_id=\"$miner_id\"}",
     "legendFormat": "Miner"
    }
   ]
  },
  {
   "title": "Daemon Total Trafic ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 193 },
   "yaxes": [
    { "format": "bps", "label": "Bits out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(lotus_net_total_in{miner_id=\"$miner_id\"}[5m])",
     "legendFormat": "Receive"
    },
    {
     "expr": "rate(lotus_net_total_out{miner_id=\"$miner_id\"}[5m])",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Daemon Total Trafic  per protocol",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 193 },
   "yaxes": [
    { "format": "bps", "label": "Bits out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(lotus_net_protocol_in{miner_id=\"$miner_id\"}[5m])",
     "legendFormat": "{{protocol}} - Receive"
    },
    {
     "expr": "rate(lotus_net_protocol_out{miner_id=\"$miner_id\"}[5m])",
     "legendFormat": "{{protocol}} - Transmit"
    }
   ]
  },
  {
   "title": "Mining Eligibility",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "lotus_power_mining_eligibility{miner_id=\"$miner_id\"}",
     "legendFormat": "Eligibility"
    }
   ]
  },
  { "title": "Worker - Ressources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 }, "repeat": "worker" },
  {
   "title": "$worker_host - CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 201 },
   "repeat": "worker_host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "lotus_miner_worker_cpu_used{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "lotus_miner_worker_cpu{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}-lotus_miner_worker_cpu_used{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "lotus_miner_worker_cpu{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "$worker_host - GPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 201 },
   "repeat": "worker_host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "lotus_miner_worker_gpu_used{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "lotus_miner_worker_gpu{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}-lotus_miner_worker_gpu_used{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "lotus_miner_worker_gpu{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "$worker_host - Physical Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 201 },
   "repeat": "worker_host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "lotus_miner_worker_mem_physical_used{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "lotus_miner_worker_mem_reserved{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "lotus_miner_worker_mem_physical{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}-(lotus_miner_worker_mem_reserved{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}+lotus_miner_worker_mem_physical_used{miner_id=\"$miner_id\", worker_host=\"$worker_host\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "lotus_miner_worker_mem_physical{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "$worker_host - VMem (Physical + Swap)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 201 },
   "repeat": "worker_host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "lotus_miner_worker_mem_vmem_used{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "lotus_miner_worker_mem_reserved{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Reserved"
    },
    {
     "expr": "(lotus_miner_worker_mem_physical{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}+lotus_miner_worker_mem_swap{miner_id=\"$miner_id\", worker_host=\"$worker_host\"})-(lotus_miner_worker_mem_reserved{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}+lotus_miner_worker_mem_vmem_used{miner_id=\"$miner_id\", worker_host=\"$worker_host\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "lotus_miner_worker_mem_physical{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}+lotus_miner_worker_mem_swap{miner_id=\"$miner_id\", worker_host=\"$worker_host\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1186 },
   "collapsed": true,
   "panels": [
    {
     "title": "$storage_id",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 73 },
     "repeat": "storage_id",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "lotus_miner_storage_capacity{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}-lotus_miner_storage_available{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}-lotus_miner_storage_reserved{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "lotus_miner_storage_reserved{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Reserved"
      },
      {
       "expr": "lotus_miner_storage_available{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "lotus_miner_storage_capacity{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$storage_id",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "lotus_miner_storage_capacity{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}-lotus_miner_storage_available{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}-lotus_miner_storage_reserved{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "lotus_miner_storage_reserved{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Reserved"
      },
      {
       "expr": "lotus_miner_storage_available{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "lotus_miner_storage_capacity{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$storage_id",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "lotus_miner_storage_capacity{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}-lotus_miner_storage_available{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}-lotus_miner_storage_reserved{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "lotus_miner_storage_reserved{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Reserved"
      },
      {
       "expr": "lotus_miner_storage_available{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "lotus_miner_storage_capacity{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$storage_id",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "lotus_miner_storage_capacity{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}-lotus_miner_storage_available{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}-lotus_miner_storage_reserved{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "lotus_miner_storage_reserved{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Reserved"
      },
      {
       "expr": "lotus_miner_storage_available{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "lotus_miner_storage_capacity{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$storage_id",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "lotus_miner_storage_capacity{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}-lotus_miner_storage_available{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}-lotus_miner_storage_reserved{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "lotus_miner_storage_reserved{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Reserved"
      },
      {
       "expr": "lotus_miner_storage_available{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "lotus_miner_storage_capacity{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$storage_id",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "lotus_miner_storage_capacity{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}-lotus_miner_storage_available{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}-lotus_miner_storage_reserved{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "lotus_miner_storage_reserved{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Reserved"
      },
      {
       "expr": "lotus_miner_storage_available{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "lotus_miner_storage_capacity{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$storage_id",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "lotus_miner_storage_capacity{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}-lotus_miner_storage_available{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}-lotus_miner_storage_reserved{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "lotus_miner_storage_reserved{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Reserved"
      },
      {
       "expr": "lotus_miner_storage_available{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "lotus_miner_storage_capacity{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$storage_id",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "lotus_miner_storage_capacity{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}-lotus_miner_storage_available{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}-lotus_miner_storage_reserved{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "lotus_miner_storage_reserved{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Reserved"
      },
      {
       "expr": "lotus_miner_storage_available{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "lotus_miner_storage_capacity{miner_id=\"$miner_id\", storage_id=\"$storage_id\"}",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1187 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scrape time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "lotus_scrape_duration_seconds{job=\"$job\",collector!=\"\"}",
       "legendFormat": "{{collector}}"
      }
     ]
    },
    {
     "title": "Chain Workers Sync Diff with ChainHead",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "lotus_chain_sync_diff{miner_id=\"$miner_id\"}",
       "legendFormat": "Worker {{ worker_id }}"
      }
     ]
    },
    {
     "title": "Power estimation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "blocks" } },
     "yaxes": [
      { "format": "blocks", "label": "blocks / day" }
     ],
     "targets": [
      {
       "expr": "sum(lotus_power{miner_id=\"$miner_id\", scope=\"miner\", power_type=\"QualityAdjPower\"})/sum(lotus_power{miner_id=\"$miner_id\", scope=\"network\",power_type=\"QualityAdjPower\"})*5*60*2*24",
       "legendFormat": "Mining rate"
      },
      {
       "expr": "sum(lotus_power{miner_id=\"$miner_id\", scope=\"miner\", power_type=\"QualityAdjPower\"})/sum(lotus_power{miner_id=\"$miner_id\", scope=\"network\",power_type=\"QualityAdjPower\"})",
       "legendFormat": "Power rate"
      }
     ]
    },
    {
     "title": "Miner Power",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes", "label": "Capacity" }
     ],
     "targets": [
      {
       "expr": "lotus_power{miner_id=\"$miner_id\", scope=\"miner\"}",
       "legendFormat": "{{power_type}}"
      },
      {
       "expr": "sum( lotus_miner_deadline_active_sectors_live{miner_id=\"$miner_id\"} * on(miner_id) group_left () lotus_miner_info_sector_size{miner_id=\"$miner_id\"})",
       "legendFormat": "Committed Power"
      }
     ]
    },
    {
     "title": "Deadlines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none", "label": "Number of dectors" }
     ],
     "targets": [
      {
       "expr": "lotus_miner_deadline_active_sectors_all{miner_id=\"$miner_id\"}",
       "legendFormat": "{{ index }} - All"
      },
      {
       "expr": "lotus_miner_deadline_active_sectors_recovering{miner_id=\"$miner_id\"}",
       "legendFormat": "{{ index }} - Recovering"
      },
      {
       "expr": "lotus_miner_deadline_active_sectors_faulty{miner_id=\"$miner_id\"}",
       "legendFormat": "{{ index }} - Faulty"
      }
     ]
    },
    {
     "title": "Stored sectors STATE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none", "label": "Sectors" }
     ],
     "targets": [
      {
       "expr": "count by (state) (lotus_miner_sector_state{miner_id=\"$miner_id\" })",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Local Mpool  Queuing msg",
     "type": "graph",
     "description": "Represent queuing message in mpool message if they don't stay in mpool more than 1 minute may not being counted",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none", "label": "Messages" }
     ],
     "targets": [
      {
       "expr": "count by (from, method) (lotus_mpool_local_message{miner_id=\"$miner_id\"})",
       "legendFormat": "{{ method }}"
      }
     ]
    },
    {
     "title": "Average Sealing Duration (From Packed to Finalized)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "yaxes": [
      { "format": "dthms" }
     ],
     "targets": [
      {
       "expr": "quantile(0.5, (topk(10,lotus_miner_sector_event{miner_id=\"$miner_id\", event_type=\"finalized\"}) - on (sector_id) lotus_miner_sector_event{miner_id=\"$miner_id\", event_type=\"packed\"}) and on(sector_id) lotus_miner_sector_state{miner_id=\"$miner_id\", state=\"Proving\"})",
       "legendFormat": "Last 10 Sectors"
      },
      {
       "expr": "quantile(0.5, (topk(100,lotus_miner_sector_event{miner_id=\"$miner_id\", event_type=\"finalized\"}) - on (sector_id) lotus_miner_sector_event{miner_id=\"$miner_id\", event_type=\"packed\"}) and on(sector_id) lotus_miner_sector_state{miner_id=\"$miner_id\", state=\"Proving\"})",
       "legendFormat": "Last 100 Sectors"
      },
      {
       "expr": "quantile(0.5, (lotus_miner_sector_event{miner_id=\"$miner_id\", event_type=\"finalized\"} - on (sector_id) lotus_miner_sector_event{miner_id=\"$miner_id\", event_type=\"packed\"}) and on(sector_id) lotus_miner_sector_state{miner_id=\"$miner_id\", state=\"Proving\"})",
       "legendFormat": "All times"
      }
     ]
    }
   ]
  }
 ]
}